### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by abrownlow21** [usgs/earthquake-global_vs30#5]
There's a broken link in the code.  In
/earthquake-global_vs30/Slope/commands_75.txt
line 7 has a link to get a zipfile that doesn't appear to exist.  Can you provide some guidance?  Thanks!

**Comment by cbworden** [comment]
The links to the gmted data seem to have moved. Here is the current list:

http://topotools.cr.usgs.gov/gmted_viewer/gmted2010_global_grids.php

I'll update the code when I get a chance.

**Comment by cbworden** [comment]
Okay, this should be fixed now.
